'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from 'react'; import { Edit3, Pin, Plus, Search, Trash2 } from 'lucide-react'; import { Button } from '@/components/ui/button'; import { Card } from '@/components/ui/card'; import { useLocalStorage } from '@/hooks/use-local-storage'; import { newId } from '@/lib/utils'; import type { JournalEntry } from '@/types';
const prompts=['What feels heaviest right now?','What would make today slightly easier?','What do you wish someone understood?','What helped you get through a difficult moment before?'];
const blank={title:'',body:'',mood:'Reflective',tags:''};
export function Journal(){const [entries,setEntries]=useLocalStorage<JournalEntry[]>('journal',[]);const [draft,setDraft]=useLocalStorage('journal-draft',blank);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<string|null>(null);const [search,setSearch]=useState('');const [filter,setFilter]=useState('All');const [deleting,setDeleting]=useState<string|null>(null);const [autosaved,setAutosaved]=useState(false);
  useEffect(()=>{if(!open)return;setAutosaved(true);const id=setTimeout(()=>setAutosaved(false),1000);return()=>clearTimeout(id)},[draft,open]);
  const filtered=useMemo(()=>entries.filter(e=>(filter==='All'||e.mood===filter)&&`${e.title} ${e.body} ${e.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(b.pinned)-Number(a.pinned)),[entries,filter,search]);
  function submit(){if(!draft.body.trim())return;const item:JournalEntry={id:editing||newId(),title:draft.title||'Untitled reflection',body:draft.body,mood:draft.mood,tags:draft.tags.split(',').map(x=>x.trim()).filter(Boolean),date:new Date().toISOString(),pinned:editing?entries.find(e=>e.id===editing)?.pinned||false:false};setEntries(x=>editing?x.map(e=>e.id===editing?item:e):[item,...x]);setDraft(blank);setEditing(null);setOpen(false)}
  function edit(e:JournalEntry){setDraft({title:e.title,body:e.body,mood:e.mood,tags:e.tags.join(', ')});setEditing(e.id);setOpen(true)}
  return <div><Card className="journal-toolbar"><div className="search"><Search/><input aria-label="Search journal" placeholder="Search private entries" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter by mood"><option>All</option><option>Reflective</option><option>Heavy</option><option>Hopeful</option><option>Calm</option></select><Button onClick={()=>setOpen(true)}><Plus size={18}/>New entry</Button></Card>
  <section className="prompt-strip" aria-label="Reflection prompts">{prompts.map(p=><button key={p} onClick={()=>{setDraft({...blank,body:p+'\n\n'});setOpen(true)}}>{p}<span>Begin →</span></button>)}</section>
  {filtered.length===0?<Card className="empty-state large"><span>✎</span><h2>Your private space is ready</h2><p>Write freely, use a prompt, or return when you feel ready. Entries are stored locally and are not encrypted.</p><Button onClick={()=>setOpen(true)}>Write an entry</Button></Card>:<div className="journal-grid">{filtered.map(e=><Card key={e.id} className="journal-entry"><div className="entry-meta"><span>{new Date(e.date).toLocaleDateString()}</span><span>{e.mood}</span></div><h2>{e.pinned&&<Pin size={15} fill="currentColor"/>}{e.title}</h2><p>{e.body}</p><div className="tag-row">{e.tags.map(t=><span className="tag" key={t}>{t}</span>)}</div><div className="entry-actions"><button onClick={()=>setEntries(x=>x.map(i=>i.id===e.id?{...i,pinned:!i.pinned}:i))}><Pin size={16}/> {e.pinned?'Unpin':'Pin'}</button><button onClick={()=>edit(e)}><Edit3 size={16}/>Edit</button><button onClick={()=>setDeleting(e.id)}><Trash2 size={16}/>Delete</button></div></Card>)}</div>}
  {open&&<div className="modal-backdrop"><section className="entry-editor" role="dialog" aria-modal="true" aria-labelledby="entry-heading"><p className="kicker">Stored on this device · not encrypted</p><h2 id="entry-heading">{editing?'Edit reflection':'New reflection'}</h2><label className="field"><span>Title</span><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Give this moment a name"/></label><label className="field"><span>What’s on your mind?</span><textarea autoFocus value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} rows={10}/></label><div className="editor-row"><label className="field"><span>Mood</span><select value={draft.mood} onChange={e=>setDraft({...draft,mood:e.target.value})}><option>Reflective</option><option>Heavy</option><option>Hopeful</option><option>Calm</option></select></label><label className="field"><span>Tags, separated by commas</span><input value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})}/></label></div><div className="row"><Button onClick={submit}>Save entry</Button><Button variant="secondary" onClick={()=>setOpen(false)}>Close</Button><small>{autosaved?'Draft saved locally':'Local autosave on'}</small></div></section></div>}
  {deleting&&<div className="mini-modal"><div><h3>Delete this journal entry?</h3><p>This cannot be undone after it is removed from this device.</p><div className="row"><Button variant="danger" onClick={()=>{setEntries(e=>e.filter(x=>x.id!==deleting));setDeleting(null)}}>Delete</Button><Button variant="secondary" onClick={()=>setDeleting(null)}>Cancel</Button></div></div></div>}
  </div>}
