'use client';

import { useState } from 'react';
import { Activity, Bell, CalendarDays, Check, ChevronRight, ClipboardCheck, Clock3, FileText, Headphones, LockKeyhole, LogOut, MessageSquareText, Phone, Search, ShieldCheck, UsersRound, Video, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';

type Role='Counsellor'|'Psychologist'|'Psychiatrist';
const patients=[
  {id:'P-2041',name:'Anonymous 2041',score:82,level:'High',signal:'Distress language increased',last:'8 min ago',consent:'Care summary + contact',mood:[42,51,49,64,82]},
  {id:'P-1837',name:'Mira S.',score:61,level:'Elevated',signal:'Low sleep, persistent worry',last:'22 min ago',consent:'Care summary',mood:[48,44,57,63,61]},
  {id:'P-1902',name:'Anonymous 1902',score:38,level:'Moderate',signal:'Work stress and isolation',last:'1 hr ago',consent:'Care summary + contact',mood:[55,49,41,36,38]},
  {id:'P-1755',name:'Kabir R.',score:19,level:'Low',signal:'Follow-up check-in',last:'Yesterday',consent:'Care summary',mood:[31,27,24,22,19]},
];
const queries=[{id:1,patient:'Anonymous 2041',text:'Can someone help me plan what to say to my family?',age:'6 min',priority:'Urgent'},{id:2,patient:'Mira S.',text:'Is my appointment available as a video consultation?',age:'18 min',priority:'Normal'},{id:3,patient:'Kabir R.',text:'Please share the grounding exercise from our last call.',age:'2 hr',priority:'Normal'}];
type Patient = typeof patients[number];

export function ProfessionalPortal(){
  const [signedIn,setSignedIn]=useState(false);const [mode,setMode]=useState<'login'|'signup'>('login');const [role,setRole]=useState<Role>('Counsellor');
  if(!signedIn)return <ProfessionalAccess mode={mode} setMode={setMode} role={role} setRole={setRole} onEnter={()=>setSignedIn(true)}/>;
  return <ProfessionalDashboard role={role} onSignOut={()=>setSignedIn(false)}/>;
}

function ProfessionalAccess({mode,setMode,role,setRole,onEnter}:{mode:'login'|'signup';setMode:(v:'login'|'signup')=>void;role:Role;setRole:(r:Role)=>void;onEnter:()=>void}){
  return <div className="professional-access"><section className="professional-welcome"><span className="professional-mark"><ShieldCheck/></span><p className="kicker">Professional care portal</p><h2>Make every response feel informed and human.</h2><p>Review consented wellbeing signals, respond to client queries, manage calls, and keep follow-up work in one calm workspace.</p><div className="professional-benefits"><span><Activity/>Prioritized care queue</span><span><Headphones/>Secure call workspace</span><span><ClipboardCheck/>Clear follow-up updates</span></div><p className="portal-disclaimer">Prototype only · No real client or clinical data</p></section><Card className="auth-card"><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Log in</button><button className={mode==='signup'?'active':''} onClick={()=>setMode('signup')}>Create account</button></div><p className="kicker">{mode==='login'?'Welcome back':'Join the care network'}</p><h2>{mode==='login'?'Access your workspace':'Professional registration'}</h2><div className="role-select" role="group" aria-label="Professional role">{(['Counsellor','Psychologist','Psychiatrist'] as Role[]).map(r=><button key={r} className={role===r?'active':''} onClick={()=>setRole(r)}>{r}</button>)}</div>{mode==='signup'&&<label className="field"><span>Full name</span><input placeholder="Dr. Your name"/></label>}<label className="field"><span>Professional email</span><input type="email" placeholder="name@clinic.org" defaultValue={mode==='login'?'demo@wellbeing.care':''}/></label><label className="field"><span>Password</span><input type="password" placeholder="At least 8 characters" defaultValue={mode==='login'?'prototype':''}/></label>{mode==='signup'&&<><label className="field"><span>Registration / licence number</span><input placeholder="Required for verification"/></label><label className="check"><input type="checkbox"/><span><b>I agree to professional and privacy standards</b><small>Credentials would be verified before live access.</small></span></label></>}<Button className="auth-submit" onClick={onEnter}>{mode==='login'?'Open demo dashboard':'Create prototype account'} <ChevronRight/></Button><p className="auth-note"><LockKeyhole/> This is a simulated access flow. Production requires verified credentials, secure authentication, audit logs, and role-based permissions.</p></Card></div>
}

function ProfessionalDashboard({role,onSignOut}:{role:Role;onSignOut:()=>void}){
  const [section,setSection]=useState('Overview');const [selected,setSelected]=useState(patients[0]);const [resolved,setResolved]=useState<number[]>([]);const [call,setCall]=useState<typeof patients[number]|null>(null);const [search,setSearch]=useState('');
  const filtered=patients.filter(p=>`${p.name} ${p.id}`.toLowerCase().includes(search.toLowerCase()));
  const nav=[['Overview',Activity],['Care queue',UsersRound],['Calls',Video],['Queries',MessageSquareText],['Appointments',CalendarDays],['Updates',Bell]] as const;
  return <div className="professional-dashboard"><aside className="professional-side"><div className="professional-brand"><span>✦</span><div><b>Wellbeing Support</b><small>Professional portal</small></div></div><nav>{nav.map(([label,Icon])=><button key={label} className={section===label?'active':''} onClick={()=>setSection(label)}><Icon/>{label}{label==='Queries'&&<span>{queries.length-resolved.length}</span>}</button>)}</nav><div className="professional-profile"><span>AS</span><div><b>Dr. Aditi Sharma</b><small>{role}</small></div><button aria-label="Sign out" onClick={onSignOut}><LogOut/></button></div></aside><main className="professional-main"><header className="professional-header"><div><p className="kicker">Tuesday, 15 September</p><h1>{section}</h1></div><div className="professional-tools"><div className="search"><Search/><input aria-label="Search clients" placeholder="Search client" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="notification"><Bell/><span>3</span></button></div></header>{section==='Overview'&&<Overview selected={selected} setSelected={setSelected} setCall={setCall}/>} {section==='Care queue'&&<CareQueue patients={filtered} selected={selected} setSelected={setSelected} setCall={setCall}/>} {section==='Queries'&&<QueryCenter resolved={resolved} setResolved={setResolved}/>} {section==='Calls'&&<Calls setCall={setCall}/>} {section==='Appointments'&&<ProfessionalAppointments/>} {section==='Updates'&&<Updates/>}</main>{call&&<CallRoom patient={call} onClose={()=>setCall(null)}/>}</div>
}

function RiskBadge({patient}:{patient:typeof patients[number]}){return <div className={`risk-score risk-${patient.level.toLowerCase()}`}><b>{patient.score}</b><span>{patient.level}</span></div>}
function Overview({selected,setSelected,setCall}:{selected:typeof patients[number];setSelected:(p:typeof patients[number])=>void;setCall:(p:typeof patients[number])=>void}){return <><div className="professional-metrics"><Card><span className="metric-icon lavender"><UsersRound/></span><div><small>Clients in queue</small><b>12</b><em>4 need review</em></div></Card><Card><span className="metric-icon peach"><Video/></span><div><small>Calls today</small><b>6</b><em>Next in 18 min</em></div></Card><Card><span className="metric-icon green"><MessageSquareText/></span><div><small>Open queries</small><b>3</b><em>1 marked urgent</em></div></Card><Card><span className="metric-icon blue"><Clock3/></span><div><small>Response time</small><b>9m</b><em>Within team goal</em></div></Card></div><div className="professional-grid"><Card className="queue-card"><div className="card-heading"><div><p className="kicker">Prioritized by prototype signal</p><h2>Client care queue</h2></div><button className="text-button">View all <ChevronRight/></button></div><div className="patient-list">{patients.map(p=><button key={p.id} className={selected.id===p.id?'active':''} onClick={()=>setSelected(p)}><span className="patient-avatar">{p.name.startsWith('Anonymous')?'A':p.name[0]}</span><span className="patient-main"><b>{p.name}</b><small>{p.signal} · {p.last}</small></span><RiskBadge patient={p}/><ChevronRight/></button>)}</div></Card><PatientPanel patient={selected} setCall={setCall}/></div></>}
function PatientPanel({patient,setCall}:{patient:typeof patients[number];setCall:(p:typeof patients[number])=>void}){return <Card className="patient-panel"><div className="patient-panel-head"><span className="patient-avatar large">{patient.name[0]}</span><div><small>{patient.id}</small><h2>{patient.name}</h2><span className="consent-pill"><Check/>Consent: {patient.consent}</span></div><RiskBadge patient={patient}/></div><div className="signal-callout"><Activity/><div><b>Current care signal</b><p>{patient.signal}. Review the conversation summary and use clinical judgment.</p></div></div><div className="signal-chart"><div className="chart-label"><span>Recent support signal</span><small>Last 5 check-ins</small></div><div className="spark-bars">{patient.mood.map((n,i)=><i key={i} style={{height:`${n}%`}}><span>{n}</span></i>)}</div></div><div className="patient-actions"><Button onClick={()=>setCall(patient)}><Video/>Start call</Button><Button variant="secondary"><FileText/>Open summary</Button><Button variant="ghost"><MessageSquareText/>Message</Button></div><p className="fine-print">This prototype score is illustrative, non-diagnostic, and never replaces clinical assessment or emergency protocol.</p></Card>}
function CareQueue({patients:queuePatients,selected,setSelected,setCall}:{patients:Patient[];selected:Patient;setSelected:(p:Patient)=>void;setCall:(p:Patient)=>void}){return <div className="professional-grid"><Card className="queue-card"><div className="card-heading"><div><p className="kicker">Consented clients</p><h2>Full care queue</h2></div><span className="queue-count">{queuePatients.length} visible</span></div><div className="patient-list">{queuePatients.map(p=><button key={p.id} className={selected.id===p.id?'active':''} onClick={()=>setSelected(p)}><span className="patient-avatar">{p.name[0]}</span><span className="patient-main"><b>{p.name}</b><small>{p.signal}</small></span><RiskBadge patient={p}/><ChevronRight/></button>)}</div></Card><PatientPanel patient={selected} setCall={setCall}/></div>}
function QueryCenter({resolved,setResolved}:{resolved:number[];setResolved:(v:number[])=>void}){return <Card className="queries-card"><div className="card-heading"><div><p className="kicker">Client messages</p><h2>Queries needing a response</h2></div><span className="queue-count">{queries.length-resolved.length} open</span></div><div className="query-list">{queries.map(q=><article key={q.id} className={resolved.includes(q.id)?'resolved':''}><span className="patient-avatar">{q.patient[0]}</span><div><div className="query-meta"><b>{q.patient}</b><span className={q.priority==='Urgent'?'urgent':''}>{q.priority}</span><small>{q.age} ago</small></div><p>{q.text}</p><div className="row"><Button variant="secondary"><MessageSquareText/>Reply</Button><Button variant="ghost" onClick={()=>setResolved([...resolved,q.id])}><Check/>{resolved.includes(q.id)?'Resolved':'Mark resolved'}</Button></div></div></article>)}</div></Card>}
function Calls({setCall}:{setCall:(p:typeof patients[number])=>void}){return <div className="schedule-layout"><Card className="today-schedule"><p className="kicker">Today’s schedule</p><h2>Calls and consultations</h2>{patients.slice(0,3).map((p,i)=><div className="schedule-item" key={p.id}><span>{['10:30','12:00','15:30'][i]}<small>{i<2?'AM':'PM'}</small></span><div><b>{p.name}</b><small>{i===1?'Follow-up · 30 min':'Initial consultation · 45 min'}</small></div><Button variant={i===0?'primary':'secondary'} onClick={()=>setCall(p)}>{i===0?'Join call':'View'}</Button></div>)}</Card><Card className="availability-card"><p className="kicker">Availability</p><h2>You’re available</h2><p>New care requests can be added to your queue until 5:30 PM.</p><label className="check"><input type="checkbox" defaultChecked/><span><b>Accept priority requests</b><small>Show me in urgent professional handoff.</small></span></label><Button variant="secondary">Manage availability</Button></Card></div>}
function ProfessionalAppointments(){return <Card className="queries-card"><p className="kicker">This week</p><h2>Appointment requests</h2>{['Mira S. · Video consultation','Anonymous 1902 · Phone follow-up','Kabir R. · In-person review'].map((x,i)=><div className="professional-appointment" key={x}><span className="date-tile"><b>{18+i}</b><small>SEP</small></span><div><b>{x}</b><small>{['11:00 AM','3:00 PM','5:30 PM'][i]} · {i?'Requested':'Confirmed'}</small></div><div className="row"><Button variant="secondary">Review</Button>{i>0&&<Button>Confirm</Button>}</div></div>)}</Card>}
function Updates(){return <Card className="queries-card"><p className="kicker">Care team activity</p><h2>Recent updates</h2><div className="update-timeline"><article><span><Activity/></span><div><b>Client signal updated</b><p>Anonymous 2041 moved from elevated to high. Manual review requested.</p><small>8 minutes ago</small></div></article><article><span><CalendarDays/></span><div><b>Appointment confirmed</b><p>Mira S. confirmed a video consultation for Friday at 11:00 AM.</p><small>34 minutes ago</small></div></article><article><span><Check/></span><div><b>Query resolved</b><p>Care coordinator shared the requested grounding resources.</p><small>2 hours ago</small></div></article></div></Card>}
function CallRoom({patient,onClose}:{patient:typeof patients[number];onClose:()=>void}){return <div className="call-overlay"><section className="call-room"><header><div><span className="live-dot"/>Prototype call room</div><button onClick={onClose} aria-label="Close call"><X/></button></header><div className="call-stage"><span className="call-avatar">{patient.name[0]}</span><h2>{patient.name}</h2><p>Ready to join · consented care context available</p></div><footer><button><Video/></button><button><MessageSquareText/></button><button className="end-call" onClick={onClose}><Phone/></button></footer><p className="call-note">No audio or video is transmitted in this frontend prototype.</p></section></div>}
